services:

  test-db:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - post

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pguser@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - post

  backend:
    image: node:22.20
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - HTTP_PORT=3000
      - POSTGRES_HOST=test-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - JWT_SECRET=SECRET
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - test-db
    networks:
      - post

  frontend:
    image: node:22.20
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment: 
      - VITE_MAIN_URL=http://localhost:3000/api
      - VITE_SERVER_URL=http://localhost:3000
    ports:
      - 5173:5173
    command: npm run dev
    depends_on:
      - backend
    networks:
      - post

networks:
  post:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:

